// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgbodpdoflhephyyzhex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpnYm9kcGRvZmxoZXBoeXl6aGV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0MjExNTEsImV4cCI6MjA5MDk5NzE1MX0.aPCRwlg7A7ZErwnMBWuvo0ZwcA7k3Ol49276PCPFVpE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});