// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { cookieStorage } from './cookieStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const STORAGE_KEY = 'sb-zgbodpdoflhephyyzhex-auth-token';

// One-time migration: promote existing localStorage session to the shared
// cookie so users currently signed in stay signed in after this change.
if (
  typeof window !== 'undefined' &&
  window.location.hostname.endsWith('kommenszlapf.website')
) {
  const existing = window.localStorage.getItem(STORAGE_KEY);
  const cookiePresent = document.cookie.includes(`${STORAGE_KEY}=`);
  if (existing && !cookiePresent) {
    cookieStorage.setItem(STORAGE_KEY, existing);
    window.localStorage.removeItem(STORAGE_KEY);
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: cookieStorage,
    storageKey: STORAGE_KEY,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});